### ISSUE TITLE
[support] Request for supporting lib for Node V12

### ISSUE THREAD

**Issue by ejahnGithub** [theupdateframework/tuf-js#167]
Try to run TUF-JS with Node V12. However, receiving this error. 

Cannot find module 'fs/promises'
Require stack:
- node_modules/cacache/lib/entry-index.js
- node_modules/cacache/lib/get.js
- node_modules/cacache/lib/index.js
- node_modules/make-fetch-happen/lib/cache/entry.js
- node_modules/make-fetch-happen/lib/cache/index.js
- node_modules/make-fetch-happen/lib/fetch.js
- node_modules/make-fetch-happen/lib/index.js
- scripts/tuf_client_fetch_target.ts

**Comment by feelepxyz** [comment]
@ejahnGithub I don't think we should support node 12 as it's no longer supported (security updates ended 8 months ago): https://endoflife.date/nodejs

Where was the support request raised from? Can't see tuf-js mentioned here and doesn't look like a lib that will depend on tuf-js?: https://github.com/iccicci/rotating-file-stream/issues/76

**Comment by ejahnGithub** [comment]
The request raised from Simon Diaz from CNCF slack channel [https://cloud-native.slack.com/archives/C8NMD3QJ3/p1673363909558969?thread_ts=1670287210.594179&cid=C8NMD3QJ3]

Sorry I was just pointing out that currently if we want TUF-JS, we would got the errors saying ```cannot find module "fs/promises" with nodejs 12.x.x" ```

**Comment by bdehamer** [comment]
@ejahnGithub if `fs/promises` is the only thing holding us back this should be pretty easy. The promis'ified versions of the `fs` functions are a nice convenience, but not critical.

**Comment by simon-id** [comment]
I'm the one that asked about a backport to node 12, as we (sadly) still support node 12 in our open source project. Once I get to using TUF, I'll take some time to investigate if more than just `fs/promises` need backporting. But as said above, if it's only promises, I can easily make a backport once I have some time for it :+1:

**Comment by feelepxyz** [comment]
Gotcha! 👍  on supporting node 12. We're working against some internal targets in the next few weeks so probably won't get it to before then so would def welcome any contributions here.

**Comment by bdehamer** [comment]
I spent a little time looking at this again. The only direct dependency we have on node 14+ is the `fs/promises` module from the standard library. 

Unfortunately, that's only half the story. Many of our dependencies have also moved on from node 12 at this point. The versions of both `jest` and `make-fetch-happen` that we're using no longer work on node 12. We could maybe work-around the `jest` issue by rolling back to an older version (though I'd really prefer not to pin ourselves to an old version), but the `make-fetch-happen` dependency is a bigger deal.

We're using `make-fetch-happen` specifically because it's the fetch library used by the npm `cli` itself. Since we're integrated w/ the `cli` now, using the same fetch library means that we aren't introducing a new dependency for that project (given the volume of npm downloads, they're sensitive to increases in the package size).

The solution for this is probably to split the default `Fetcher` into a separate package, so that consumers could provide their own implementation (with whatever underlying HTTP client they want).

Given that this is a lot more complex than I initially though I'm not going to pursue this any further. I'm happy to look at PRs if someone wants to pick this up and try to sort it out.
